repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.0.285
  hooks:
    - id: ruff
      args:
      - --fix


-   repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
    -   id: black

-   repo: local
    hooks:
    -   id: mypy
        name: Run mypy
        entry: mypy garlic
        language: system
        types: [python]
        always_run: true
        pass_filenames: false
    -   id: pytest
        name: Run pytest
        entry: pytest
        language: system
        types: [python]
        always_run: true
        pass_filenames: false





