repos:
-   repo: local
    hooks:
    -   id: check-version-upgrade
        name: Check version upgrade
        entry: ./scripts/upgrade_version_check.sh
        language: script
        always_run: true
        pass_filenames: false

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.0.285
  hooks:
    - id: ruff
      args:
      - --fix


-   repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
    -   id: black

-   repo: local
    hooks:
    -   id: pytest
        name: Run pytest
        entry: pytest
        language: system
        types: [python]
        always_run: true
        pass_filenames: false





