repos:
-   repo: local
    hooks:
    -   id: check-commit-prefix-and-branch
        name: Check version upgrade
        entry: ./scripts/upgrade_version_check.sh
        language: script
        always_run: true
        pass_filenames: false
    -   id: pytest
        name: Run pytest
        entry: pytest
        language: system
        types: [python]
        always_run: true
        pass_filenames: false

